name: Deploy to EC2

on:
  push:
    branches:
      - main # Or replace with the branch you want to deploy from

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Deploy to EC2 via SSH
      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu # Default username for Ubuntu AMI
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /var/www/html/lafia-backend  
            git pull origin main  
            sudo pm2 restart app || sudo systemctl restart your-service
